spring:
  profiles: dev

  loggin:
    level:
      org.springframework.web.info

  datasource:
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
    jdbc-url: jdbc:mariadb://carbon-zero-dev.cdspom5j0apx.ap-northeast-2.rds.amazonaws.com:3306/carbon-zero-dev
    username: carbon_zero_dev
    password: carbon_zero_dev

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
    show-sql: true
