-- ROOT
INSERT INTO CATEGORY VALUES (1, 0, '패션의류/잡화', NULL);
INSERT INTO CATEGORY VALUES (2, 0, '뷰티', NULL);
INSERT INTO CATEGORY VALUES (3, 0, '출산/유아동', NULL);
INSERT INTO CATEGORY VALUES (4, 0, '식품', NULL);
INSERT INTO CATEGORY VALUES (5, 0, '주방용품', NULL);
INSERT INTO CATEGORY VALUES (6, 0, '생활용품', NULL);
INSERT INTO CATEGORY VALUES (7, 1, '헤어/바디/세안', 6);
INSERT INTO CATEGORY VALUES (8, 1, '샴푸/린스', 7);
INSERT INTO CATEGORY VALUES (9, 1, '구강/면도', 6);


